In [1]:
import numpy as np
import tensorflow as tf

In [5]:
x = tf.constant([0, 1, 2])

In [6]:
tf.print(x.shape)

TensorShape([3])


In [7]:
weights = tf.constant([[0, 1], [2, 3], [4, 5]])

In [11]:
tf.matmul(tf.expand_dims(x, axis=0), weights)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10, 13]], dtype=int32)>

In [12]:
tf.matmul(x, weights)

InvalidArgumentError: In[0] and In[1] has different ndims: [3] vs. [3,2] [Op:MatMul]

In [13]:
prod = tf.constant([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
bias = tf.constant([1, 1, 1])

In [14]:
prod + bias

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>