In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [15]:
embeddings = tf.constant([[0, 1, 2], [3, 4, 5]], dtype='float32')

In [16]:
context_embeddings = tf.nn.embedding_lookup(embeddings, [0, 1])

In [17]:
avg_context_embeddings = tf.reduce_mean(context_embeddings, axis=0)

In [18]:
avg_context_embeddings

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.5, 2.5, 3.5], dtype=float32)>

In [19]:
embeddings

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)>

In [21]:
embeddings_norms = tf.norm(embeddings, axis=1)

In [23]:
embeddings embeddings_norms

SyntaxError: invalid syntax (<ipython-input-23-7b23875b8e8c>, line 1)

In [24]:
tf.math.reduce_euclidean_norm(embeddings, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.236068, 7.071068], dtype=float32)>

In [25]:
embeddings

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)>

In [26]:
tf.linalg.normalize(embeddings, axis=1)

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0.        , 0.4472136 , 0.8944272 ],
        [0.42426407, 0.56568545, 0.70710677]], dtype=float32)>,
 <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[2.236068],
        [7.071068]], dtype=float32)>)

In [38]:
norm_embeddings = tf.linalg.normalize(embeddings, axis=1)
print(norm_embeddings)

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.        , 0.4472136 , 0.8944272 ],
       [0.42426407, 0.56568545, 0.70710677]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.236068],
       [7.071068]], dtype=float32)>)


In [30]:
word_embedding = tf.nn.embedding_lookup(embeddings, 0)

In [55]:
norm_word_embedding = tf.linalg.normalize(word_embedding)[0]
print(norm_word_embedding)
norm_word_embedding.shape

tf.Tensor([0.        0.4472136 0.8944272], shape=(3,), dtype=float32)


TensorShape([3])

In [54]:
tf.shape(norm_word_embedding[0])

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [48]:
tf.linalg.matvec(norm_embeddings, norm_word_embedding)

InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [3] != values[1].shape = [1] [Op:Pack] name: packed

In [41]:
cos_sims = tf.matmul(norm_embeddings, tf.expand_dims(norm_word_embedding, axis=1))

InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [3] != values[1].shape = [1] [Op:Pack] name: packed