In [1]:
# Understanding whether tensors are created as rows or columns
import numpy as np
import tensorflow as tf

In [6]:
weights = tf.Variable(tf.initializers.glorot_uniform()(shape=(20,), dtype=tf.float64), \
                                   name='weights')

In [7]:
weights.shape

TensorShape([20])

In [8]:
# A row vector
tf.print(weights)

[0.34990862403918188 -0.37663765898377255 0.33626562996801557 ... -0.082545945871389192 -0.13676532667962588 -0.34527652197111697]


In [9]:
examples = tf.Variable(tf.initializers.glorot_uniform()(shape=(10, 20), dtype=tf.float64), \
                                   name='weights')

In [10]:
examples.shape

TensorShape([10, 20])

In [13]:
# 10 rows, 20 columns
examples[0].shape

TensorShape([20])

In [18]:
# shape(20,) means a row vector of 20 elements (1 x 20, but without the row dimension)
# shape(10, 20) means a 10 x 20 vector
tf.matmul(examples, tf.transpose(tf.expand_dims(weights, axis=0)))

<tf.Tensor: shape=(10, 1), dtype=float64, numpy=
array([[ 0.17025158],
       [-0.21096546],
       [ 0.39264935],
       [ 0.10279641],
       [ 0.38708733],
       [-0.03871561],
       [-0.014994  ],
       [-0.55635068],
       [ 0.24659386],
       [ 0.39105183]])>

In [22]:
weights = tf.Variable(tf.initializers.glorot_uniform()(shape=(1, 10), dtype=tf.float64), \
                                   name='weights')
bias = tf.Variable(tf.zeros_initializer()(shape=(10,), dtype=tf.float64), name='bias')

In [23]:
weights + bias

<tf.Tensor: shape=(1, 10), dtype=float64, numpy=
array([[ 0.64049819,  0.0077094 , -0.57953352,  0.32541715, -0.55398953,
        -0.34048255,  0.10216706, -0.50760297, -0.10007871, -0.36271382]])>

In [24]:
indices = tf.constant([1, 2, 3, 4])

In [25]:
tf.one_hot(indices, 10)

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>