In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.keras

In [8]:
embeddings = tf.Variable(tf.initializers.glorot_uniform()(shape=(10, 4)))

In [9]:
embeddings

<tf.Variable 'Variable:0' shape=(10, 4) dtype=float32, numpy=
array([[ 0.5261166 ,  0.18858218,  0.21261919,  0.56117153],
       [ 0.14620614, -0.49192286, -0.09956354,  0.27477008],
       [-0.2852441 , -0.3607269 ,  0.38431728, -0.21654934],
       [ 0.35983133, -0.39179555,  0.12253249, -0.21574146],
       [ 0.00878239, -0.14678568,  0.1319381 ,  0.4768026 ],
       [ 0.6285664 , -0.33480984, -0.22057763,  0.45323086],
       [ 0.34550142, -0.19282335,  0.01585007,  0.11388558],
       [-0.4974628 , -0.24138954, -0.36911455,  0.4419886 ],
       [-0.5021223 ,  0.18120527,  0.21738017,  0.2787093 ],
       [ 0.32135904, -0.27003863, -0.6149886 , -0.03032559]],
      dtype=float32)>

In [12]:
context = tf.constant([[0, 1], [2, 4], [2, 5]])
context_embeddings = tf.nn.embedding_lookup(embeddings, context)

In [13]:
tf.shape(context_embeddings)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 4], dtype=int32)>

In [14]:
context_embeddings

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[ 0.5261166 ,  0.18858218,  0.21261919,  0.56117153],
        [ 0.14620614, -0.49192286, -0.09956354,  0.27477008]],

       [[-0.2852441 , -0.3607269 ,  0.38431728, -0.21654934],
        [ 0.00878239, -0.14678568,  0.1319381 ,  0.4768026 ]],

       [[-0.2852441 , -0.3607269 ,  0.38431728, -0.21654934],
        [ 0.6285664 , -0.33480984, -0.22057763,  0.45323086]]],
      dtype=float32)>

In [15]:
# shape: (batch_size, 2, embedding_size)
# average across dimension 1

In [16]:
avg_context = tf.reduce_mean(context_embeddings, axis=1)

In [17]:
tf.shape(avg_context)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [18]:
avg_context

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.33616138, -0.15167034,  0.05652782,  0.4179708 ],
       [-0.13823086, -0.25375628,  0.2581277 ,  0.13012663],
       [ 0.17166114, -0.34776837,  0.08186983,  0.11834076]],
      dtype=float32)>

In [19]:
word = tf.constant([0, 1, 2])
word_embeddings = tf.nn.embedding_lookup(embeddings, word)

In [20]:
tf.shape(word_embeddings)
# shape: (batch_size, embedding_size)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>